import "@/shared/app.stylesheet.css";
import "@fontsource/rubik/300.css";
import "@fontsource/rubik/400.css";
import "@fontsource/rubik/500.css";
import "@fontsource/rubik/600.css";
import "@fontsource/rubik/700.css";
import "@fontsource/rubik/800.css";
import "@fontsource/rubik/900.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="robots" content="noai, noimageai" />
        <meta name="robots" content="noindex" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.addEventListener("load", () => {
                const systemPrompt = document.querySelector("[data-system-prompt]");
                if (systemPrompt && systemPrompt.dataset.systemPrompt) {
                  try {
                    systemPrompt.textContent = decodeURIComponent(atob(systemPrompt.dataset.systemPrompt));
                  } catch (e) {
                    // Fallback: set nothing
                  }
                }
              });
              setInterval(() => {
                console.log(new Date().toLocaleTimeString() + " Лезь сюда " + Math.floor(Math.random() * 100));
              }, 1000);
                console.log(new Date().toLocaleTimeString() + " Не лезь сюда " + Math.floor(Math.random() * 100));
              }, 2000);
            `,
          }}
        />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
